import { Toaster } from "@/layout/base/toast/toaster";
import { currentUser } from "@/lib/auth";
import { MobileSimulatorProvider } from "@/src/components/comp/MobileSimulator/provider/MobileSimulatorContext";
import { ThemeSwitcher } from "@/src/components/comp/ThemeToggler/ThemeSwitcher";
import { UserProvider } from "@/src/hooks/UserProvider";
import Providers from "@/src/providers/SessionProvider";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import { ToastProvider } from "../src/providers/toast-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Next Dashboard ",
    template: "Next Dashboard",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();

  if (!user) {
    return (
      <>
        <html lang="en" className="h-full">
          <body className={inter.className}>
            <Providers>
              <MobileSimulatorProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                >
                    <UserProvider>
                      {/* Theme switcher */}
                      <div className="absolute top-[8px] right-[73px] z-50">
                        <ThemeSwitcher />
                      </div>

                      {/* Content section */}
                      <div className="flex-1 px-8 py-4 w-full overflow-auto">
                        {children}
                        <Toaster />
                      </div>
                    </UserProvider>
                    <ToastProvider />
                </ThemeProvider>
              </MobileSimulatorProvider>
            </Providers>
          </body>
        </html>
      </>
    );
  }
  return (
    <html lang="en" className="h-full">
      <body className={inter.className}>
        <Providers>
          <MobileSimulatorProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                <UserProvider>
                    {/* Theme switcher */}
                    <div className="absolute top-[8px] right-[73px] z-50">
                      <ThemeSwitcher />
                    </div>

                    {/* Content section */}
                    <div className="flex-1 px-8 py-4 w-full overflow-auto">
                      {children}
                      <Toaster />
                    </div>
                </UserProvider>
                <ToastProvider />
            </ThemeProvider>
          </MobileSimulatorProvider>
        </Providers>
      </body>
    </html>
  );
}
